name: beautydesign
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sqflite: ^1.3.0
  bottom_navy_bar: ^5.4.0
  font_awesome_flutter: ^8.8.1
  mask_text_input_formatter: ^1.0.6
  flutter_datetime_picker: ^1.3.8
  lite_rolling_switch: ^0.1.1
  simple_animations: ^2.2.0
  auto_size_text: ^2.1.0
  signature: ^3.1.1
  firebase_core: ^0.4.4+3 #recursos básicos
  #cloud_firestore: ^0.13.5 #banco de dados
  firebase_storage: ^3.1.5 #armazenamento de arquivos
  firebase_auth: ^0.16.0 #autenticação do usuario
  validate: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Neutra
      fonts:
        - asset: assets/fonts/Neutra2Text-Light.otf
          weight: 300
        - asset: assets/fonts/Neutra2Text-Book.otf
          weight: 400
        - asset: assets/fonts/Neutra2Text-Demi.otf
          weight: 500
        - asset: assets/fonts/Neutra2Text-Bold.otf
          weight: 700

    - family: Sinthya
      fonts:
        - asset: assets/fonts/Sinthya.ttf
        - asset: assets/fonts/Sinthya.ttf
          weight: 400

  assets:
    - assets/img/capa.png